In [1]:
import pandas as pd
import sys
import os

# Obtener la ruta absoluta de la carpeta 'notebooks'
notebook_dir = os.getcwd()

# Subir un nivel para llegar a la raíz del proyecto ('cuentas')
project_root = os.path.dirname(notebook_dir)

# Añadir la raíz del proyecto a la ruta de búsqueda de Python
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# TXT

In [26]:
txt_files_names = ["atipicos.txt","diferencias_atipicas.txt","diferencias_atipicas2.txt"]

df_unido_txt = pd.DataFrame()
for txt_file in txt_files_names:
    path = os.path.join(project_root, "data", "descripciones", txt_file)
    # Leer el archivo de texto y convertirlo en un DataFrame de pandas
    
    if df_unido_txt.empty:
        df_unido_txt = pd.read_csv(path, sep="\t")
        df = pd.DataFrame()
    else:
        df = pd.read_csv(path, sep="\t")
    print(df)
    df_unido_txt = pd.concat([df_unido_txt, df], ignore_index=True)
    
    # # Guardar el DataFrame como un archivo CSV
    # csv_file = txt_file.replace(".txt", ".csv")
    # df.to_csv(csv_file, index=False, header=False)
df_unido_txt
df_unido_txt.sort_values(by="FECHA", inplace=True)

Empty DataFrame
Columns: []
Index: []
         FECHA  diff_total_yo  diff_tarjeta  diff_saldo_real  \
0   2024-03-25         279.00          0.00           279.00
1   2024-03-29        -156.69        156.69             0.00
2   2024-04-01         -27.31          0.00           -27.31
3   2024-04-02         -28.84         15.84           -13.00
4   2024-04-05         -26.68         26.68             0.00
..         ...            ...           ...              ...
80  2025-04-20         -23.00         23.00             0.00
81  2025-04-21         -58.60         14.60           -44.00
82  2025-04-23          88.80          7.70            96.50
83  2025-04-29         -22.92          0.00           -22.92
84  2025-05-01         -34.39         29.29            -5.10

                                          descripcion
0                                       Deposito 280
1   Pycca Portal , supermaxi mc -155 #En verdad py...
2                        transferencia -40 #No cuadra
3                              Kfc y transferecia -27
4                                              MC -26
..                                                ...
80                                            ChatGPT
81                       car wash 23 y no se .tablita
82             Transferencia madre 100 &mensual madre
83                  Viernes leo y comida #desde el 25
84   uber eats y google cloud #uber del 25 &pagado 26

[85 rows x 5 columns]
         FECHA  diff_total_yo  diff_tarjeta  diff_saldo_real  \
0   2024-03-25         280.00          0.00           280.00
1   2024-03-28        -134.43        134.43             0.00
2   2024-03-29         -22.26         22.26             0.00
3   2024-04-01         -39.31          0.00           -39.31
4   2024-04-05         -26.68         26.68             0.00
..         ...            ...           ...              ...
90  2025-04-17         -93.42          8.92           -84.50
91  2025-04-20         -23.00         23.00             0.00
92  2025-04-21         -58.60         14.60           -44.00
93  2025-04-23          88.80          7.70            96.50
94  2025-04-28         -39.47         26.30           -13.17

                          descripcion               comentario          madre
0                       Deposito 280                       NaN            NaN
1                                 NaN                      NaN            NaN
2   Pycca Portal , supermaxi mc -155   En verdad pycca es -28             NaN
3                  transferencia -40                 No cuadra            NaN
4                              MC -26                      NaN            NaN
..                                ...                      ...            ...
90    partido y me pagan en efectivo                       NaN            NaN
91                            ChatGPT                      NaN            NaN
92       car wash 23 y no se .tablita                      NaN            NaN
93           Transferencia madre 100                       NaN  mensual madre
94                                NaN                      NaN            NaN

[95 rows x 7 columns]

In [13]:
df_unido[["FECHA","diff_saldo_real","descripcion","comentario","madre"]].head(20)

,FECHA,diff_saldo_real,descripcion,comentario,madre
0,2024-03-25,279.00,Deposito 280,NaN,NaN
86,2024-03-25,279.00,Deposito 280,NaN,NaN
171,2024-03-25,280.00,Deposito 280,NaN,NaN
172,2024-03-28,0.00,NaN,NaN,NaN
1,2024-03-29,0.00,"Pycca Portal , supermaxi mc -155 #En verdad py...",NaN,NaN
87,2024-03-29,0.00,"Pycca Portal , supermaxi mc -155 #En verdad py...",NaN,NaN
173,2024-03-29,0.00,"Pycca Portal , supermaxi mc -155",En verdad pycca es -28,NaN
88,2024-04-01,-27.31,transferencia -40 #No cuadra,NaN,NaN
2,2024-04-01,-27.31,transferencia -40 #No cuadra,NaN,NaN
174,2024-04-01,-39.31,transferencia -40,No cuadra,NaN
89,2024-04-02,-13.00,Kfc y transferecia -27,NaN,NaN
3,2024-04-02,-13.00,Kfc y transferecia -27,NaN,NaN
90,2024-04-05,0.00,MC -26,NaN,NaN
4,2024-04-05,0.00,MC -26,NaN,NaN
175,2024-04-05,0.00,MC -26,NaN,NaN
91,2024-04-08,3.00,Difare? y Sime -32,NaN,NaN
5,2024-04-08,3.00,Difare? y Sime -32,NaN,NaN
176,2024-04-08,2.10,Difare? y Sime -32,NaN,NaN
6,2024-04-11,-45.90,ChatGpt Difare y Sime -37 &Pagado,NaN,NaN
92,2024-04-11,-45.90,ChatGpt Difare y Sime -37 &Pagado,NaN,NaN

# XLSX

In [27]:
txt_files_names = ["completo2026_01_14.xlsx", "completo_2025-09-20.xlsx", "diferencias_2025-09-20.xlsx", "diferencias_atipicas3.xlsx"]
lista_dfs = [] # Es mejor guardar todo en una lista y concatenar al final

for file_name in txt_files_names:
    path = os.path.join(project_root, "data", "descripciones", file_name)
    
    # IMPORTANTE: Usamos read_excel porque la extensión es .xlsx
    try:
        df = pd.read_excel(path)
        print(f"Leído exitosamente: {file_name}")
        lista_dfs.append(df)
    except Exception as e:
        print(f"Error al leer {file_name}: {e}")

# Concatenamos todos los DataFrames de la lista
if lista_dfs:
    df_unido_xlsx = pd.concat(lista_dfs, ignore_index=True)
    
    # Asegúrate de que la columna FECHA sea de tipo datetime antes de ordenar
    df_unido_xlsx['FECHA'] = pd.to_datetime(df_unido_xlsx['FECHA'], errors='coerce')
    df_unido_xlsx.sort_values(by="FECHA", inplace=True)
    
    print("\nDataFrame unido y ordenado por fecha:")
    print(df_unido_xlsx.head())
else:
    print("No se cargó ningún dato.")

Leído exitosamente: completo2026_01_14.xlsx
Leído exitosamente: completo_2025-09-20.xlsx
Leído exitosamente: diferencias_2025-09-20.xlsx
Leído exitosamente: diferencias_atipicas3.xlsx

DataFrame unido y ordenado por fecha:
         FECHA  TOTAL  SALDO  TARJETA  INVERSION  PAGOS_MENSUAL_MA INTER  \
535 2024-06-21    NaN    NaN      NaN        NaN                     NaN
536 2024-06-22    NaN    NaN      NaN        NaN                     NaN
537 2024-06-24    NaN    NaN      NaN        NaN                     NaN
538 2024-06-25    NaN    NaN      NaN        NaN                     NaN
539 2024-07-04    NaN    NaN      NaN        NaN                     NaN

     NOTIONCUM DESCRIPCION MADRE  diff_TOTAL  diff_tarjeta  \
535        NaN         NaN   NaN         NaN         31.97
536        NaN         NaN   NaN         NaN        102.52
537        NaN         NaN   NaN         NaN          5.99
538        NaN         NaN   NaN         NaN          0.00
539        NaN         NaN   NaN         NaN          0.00

     diff_saldo_sin_inversion  diff_notion DESCRIPCION_NOTION comentario  \
535                       NaN          NaN                NaN        NaN
536                       NaN          NaN                NaN        NaN
537                       NaN          NaN                NaN        NaN
538                       NaN          NaN                NaN        NaN
539                       NaN          NaN                NaN        NaN

     diff_total_yo  diff_saldo_real                      descripcion   madre
535         -31.97             0.00                    Casa res mela     NaN
536        -102.52             0.00                           Carro   pagado
537          71.92            77.91                     Poo me pagan     NaN
538         -62.75           -62.75                     Pastillas 60     NaN
539         -29.35           -29.35  Tienda trago 15,De una padel 14     NaN

In [29]:
df_unido = pd.concat([df_unido_txt, df_unido_xlsx], ignore_index=True)
df_unido['FECHA'] = pd.to_datetime(df_unido['FECHA'], errors='coerce')
df_unido.sort_values(by="FECHA", inplace=True)

In [32]:
df_unido.head(20)

,FECHA,diff_total_yo,diff_tarjeta,diff_saldo_real,descripcion,comentario,madre,TOTAL,SALDO,TARJETA,INVERSION,PAGOS_MENSUAL_MA INTER,NOTIONCUM,DESCRIPCION,MADRE,diff_TOTAL,diff_saldo_sin_inversion,diff_notion,DESCRIPCION_NOTION
0,2024-03-25,279.00,0.00,279.00,Deposito 280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-03-25,279.00,0.00,279.00,Deposito 280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-03-25,280.00,0.00,280.00,Deposito 280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-03-28,-134.43,134.43,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-03-29,-156.69,156.69,0.00,"Pycca Portal , supermaxi mc -155 #En verdad py...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-03-29,-156.69,156.69,0.00,"Pycca Portal , supermaxi mc -155 #En verdad py...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-03-29,-22.26,22.26,0.00,"Pycca Portal , supermaxi mc -155",En verdad pycca es -28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-04-01,-27.31,0.00,-27.31,transferencia -40 #No cuadra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-04-01,-27.31,0.00,-27.31,transferencia -40 #No cuadra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-04-01,-39.31,0.00,-39.31,transferencia -40,No cuadra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2024-04-02,-28.84,15.84,-13.00,Kfc y transferecia -27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2024-04-02,-28.84,15.84,-13.00,Kfc y transferecia -27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2024-04-05,-26.68,26.68,0.00,MC -26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2024-04-05,-26.68,26.68,0.00,MC -26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024-04-05,-26.68,26.68,0.00,MC -26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2024-04-08,-29.50,32.50,3.00,Difare? y Sime -32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2024-04-08,-29.50,32.50,3.00,Difare? y Sime -32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2024-04-08,-30.40,32.50,2.10,Difare? y Sime -32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2024-04-11,-83.12,37.22,-45.90,ChatGpt Difare y Sime -37 &Pagado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2024-04-11,-83.12,37.22,-45.90,ChatGpt Difare y Sime -37 &Pagado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df_unido[["FECHA","diff_total_yo","descripcion","comentario","madre","DESCRIPCION","MADRE","DESCRIPCION_NOTION"]].query("FECHA > '2024-12-10'").head(20)

,FECHA,diff_total_yo,descripcion,comentario,madre,DESCRIPCION,MADRE,DESCRIPCION_NOTION
300,2024-12-11,-157.04,Derma,NaN,no pagado,NaN,NaN,NaN
156,2024-12-11,-157.04,Derma,NaN,no pagado,NaN,NaN,NaN
155,2024-12-11,-157.04,Derma &no pagado,NaN,NaN,NaN,NaN,NaN
154,2024-12-11,-157.04,Derma &no pagado,NaN,NaN,NaN,NaN,NaN
301,2024-12-13,-35.90,Farmacias 32,NaN,pagado,NaN,NaN,NaN
157,2024-12-13,-35.90,Farmacias &pagado,NaN,NaN,NaN,NaN,NaN
158,2024-12-13,-35.90,Farmacias &pagado,NaN,NaN,NaN,NaN,NaN
159,2024-12-13,-35.90,Farmacias,NaN,pagado,NaN,NaN,NaN
162,2024-12-23,-59.69,Regalos navidad,NaN,NaN,NaN,NaN,NaN
161,2024-12-23,-59.69,Regalos navidad,NaN,NaN,NaN,NaN,NaN
302,2024-12-23,-59.69,Regalos 48,NaN,NaN,NaN,NaN,NaN
160,2024-12-23,-59.69,Regalos navidad,NaN,NaN,NaN,NaN,NaN
165,2024-12-24,-52.01,"Mega,salsa pavo y mc &pagado 22",NaN,NaN,NaN,NaN,NaN
164,2024-12-24,-52.01,"Mega,salsa pavo y mc",NaN,pagado 22,NaN,NaN,NaN
163,2024-12-24,-52.01,"Mega,salsa pavo y mc &pagado 22",NaN,NaN,NaN,NaN,NaN
303,2024-12-24,-52.01,"Super 33 mc 5, salsa pavo 5 . Tienda 6",NaN,pagado 22,NaN,NaN,NaN
167,2024-12-27,50.00,Trasnferencia nico,NaN,NaN,NaN,NaN,NaN
166,2024-12-27,50.00,Trasnferencia nico,NaN,NaN,NaN,NaN,NaN
304,2024-12-27,47.50,Trasnferencia nico 50,NaN,NaN,NaN,NaN,NaN
168,2024-12-27,47.50,Trasnferencia nico,NaN,NaN,NaN,NaN,NaN

In [45]:
#Escrbir df_unido en data/descripciones/df_unido.csv
output_path = os.path.join(project_root, "data", "descripciones", "df_unido.csv")
df_unido.to_csv(output_path, index=False)