In [1]:
import pandas as pd
import sys
import os

# Obtener la ruta absoluta de la carpeta 'notebooks'
notebook_dir = os.getcwd()

# Subir un nivel para llegar a la raíz del proyecto ('cuentas')
project_root = os.path.dirname(notebook_dir)

# Añadir la raíz del proyecto a la ruta de búsqueda de Python
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# TXT

In [ ]:
txt_files_names = ["atipicos.txt","diferencias_atipicas.txt","diferencias_atipicas2.txt"]

df_unido_txt = pd.DataFrame()
for txt_file in txt_files_names:
    path = os.path.join(project_root, "data", "descripciones", txt_file)
    # Leer el archivo de texto y convertirlo en un DataFrame de pandas
    
    if df_unido_txt.empty:
        df_unido_txt = pd.read_csv(path, sep="\t")
        df = pd.DataFrame()
    else:
        df = pd.read_csv(path, sep="\t")
    print(df)
    df_unido_txt = pd.concat([df_unido_txt, df], ignore_index=True)
    
    # # Guardar el DataFrame como un archivo CSV
    # csv_file = txt_file.replace(".txt", ".csv")
    # df.to_csv(csv_file, index=False, header=False)
df_unido_txt
df_unido_txt.sort_values(by="FECHA", inplace=True)

Empty DataFrame
Columns: []
Index: []
         FECHA  diff_total_yo  diff_tarjeta  diff_saldo_real  \
0   2024-03-25         279.00          0.00           279.00
1   2024-03-29        -156.69        156.69             0.00
2   2024-04-01         -27.31          0.00           -27.31
3   2024-04-02         -28.84         15.84           -13.00
4   2024-04-05         -26.68         26.68             0.00
..         ...            ...           ...              ...
80  2025-04-20         -23.00         23.00             0.00
81  2025-04-21         -58.60         14.60           -44.00
82  2025-04-23          88.80          7.70            96.50
83  2025-04-29         -22.92          0.00           -22.92
84  2025-05-01         -34.39         29.29            -5.10

                                          descripcion
0                                       Deposito 280
1   Pycca Portal , supermaxi mc -155 #En verdad py...
2                        transferencia -40 #No cuadra
3                              Kfc y transferecia -27
4                                              MC -26
..                                                ...
80                                            ChatGPT
81                       car wash 23 y no se .tablita
82             Transferencia madre 100 &mensual madre
83                  Viernes leo y comida #desde el 25
84   uber eats y google cloud #uber del 25 &pagado 26

[85 rows x 5 columns]
         FECHA  diff_total_yo  diff_tarjeta  diff_saldo_real  \
0   2024-03-25         280.00          0.00           280.00
1   2024-03-28        -134.43        134.43             0.00
2   2024-03-29         -22.26         22.26             0.00
3   2024-04-01         -39.31          0.00           -39.31
4   2024-04-05         -26.68         26.68             0.00
..         ...            ...           ...              ...
90  2025-04-17         -93.42          8.92           -84.50
91  2025-04-20         -23.00         23.00             0.00
92  2025-04-21         -58.60         14.60           -44.00
93  2025-04-23          88.80          7.70            96.50
94  2025-04-28         -39.47         26.30           -13.17

                          descripcion               comentario          madre
0                       Deposito 280                       NaN            NaN
1                                 NaN                      NaN            NaN
2   Pycca Portal , supermaxi mc -155   En verdad pycca es -28             NaN
3                  transferencia -40                 No cuadra            NaN
4                              MC -26                      NaN            NaN
..                                ...                      ...            ...
90    partido y me pagan en efectivo                       NaN            NaN
91                            ChatGPT                      NaN            NaN
92       car wash 23 y no se .tablita                      NaN            NaN
93           Transferencia madre 100                       NaN  mensual madre
94                                NaN                      NaN            NaN

[95 rows x 7 columns]

In [13]:
df_unido[["FECHA","diff_saldo_real","descripcion","comentario","madre"]].head(20)

,FECHA,diff_saldo_real,descripcion,comentario,madre
0,2024-03-25,279.00,Deposito 280,NaN,NaN
86,2024-03-25,279.00,Deposito 280,NaN,NaN
171,2024-03-25,280.00,Deposito 280,NaN,NaN
172,2024-03-28,0.00,NaN,NaN,NaN
1,2024-03-29,0.00,"Pycca Portal , supermaxi mc -155 #En verdad py...",NaN,NaN
87,2024-03-29,0.00,"Pycca Portal , supermaxi mc -155 #En verdad py...",NaN,NaN
173,2024-03-29,0.00,"Pycca Portal , supermaxi mc -155",En verdad pycca es -28,NaN
88,2024-04-01,-27.31,transferencia -40 #No cuadra,NaN,NaN
2,2024-04-01,-27.31,transferencia -40 #No cuadra,NaN,NaN
174,2024-04-01,-39.31,transferencia -40,No cuadra,NaN
89,2024-04-02,-13.00,Kfc y transferecia -27,NaN,NaN
3,2024-04-02,-13.00,Kfc y transferecia -27,NaN,NaN
90,2024-04-05,0.00,MC -26,NaN,NaN
4,2024-04-05,0.00,MC -26,NaN,NaN
175,2024-04-05,0.00,MC -26,NaN,NaN
91,2024-04-08,3.00,Difare? y Sime -32,NaN,NaN
5,2024-04-08,3.00,Difare? y Sime -32,NaN,NaN
176,2024-04-08,2.10,Difare? y Sime -32,NaN,NaN
6,2024-04-11,-45.90,ChatGpt Difare y Sime -37 &Pagado,NaN,NaN
92,2024-04-11,-45.90,ChatGpt Difare y Sime -37 &Pagado,NaN,NaN

# XLSX

In [18]:
import chardet

In [23]:
txt_files_names = ["completo2026_01_14.xlsx","completo_2025-09-20.xlsx","diferencias_2025-09-20.xlsx","diferencias_atipicas3.xlsx"]

df_unido = pd.DataFrame()
for txt_file in txt_files_names:
    path = os.path.join(project_root, "data", "descripciones", txt_file)
    # Leer el archivo de texto y convertirlo en un DataFrame de pandas
    
    if df_unido.empty:
        df_unido = pd.read_excel(path)
        df = pd.DataFrame()
    else:
        df = pd.read_excel(path)
    print(df)
    df_unido = pd.concat([df_unido, df], ignore_index=True)
    
    # # Guardar el DataFrame como un archivo CSV
    # csv_file = txt_file.replace(".txt", ".csv")
    # df.to_csv(csv_file, index=False, header=False)
df_unido
df_unido.sort_values(by="FECHA", inplace=True)

Empty DataFrame
Columns: []
Index: []
          FECHA   TOTAL   SALDO  TARJETA  INVERSION  PAGOS_MENSUAL_MA INTER  \
0    2025-01-06     NaN  759.79   295.27     -600.0                    0.00
1    2025-01-07     NaN  739.79   295.27     -600.0                    1.04
2    2025-01-08     NaN  739.79   295.27     -600.0                    2.08
3    2025-01-09     NaN  733.79   295.27     -600.0                    3.12
4    2025-01-10     NaN  699.76   295.27     -600.0                    4.17
..          ...     ...     ...      ...        ...                     ...
179  2025-09-09 -407.19  177.67   273.23     1034.0                    0.00
180  2025-09-10 -411.19  173.67   273.23     1034.0                    0.00
181  2025-09-14 -391.19  173.67   273.23     1034.0                    0.00
182  2025-09-15 -386.69  173.67   273.23     1034.0                    0.00
183  2025-09-16 -366.69  173.67   273.23     1034.0                    0.00

     NOTIONCUM          DESCRIPCION MADRE
0       186.23                  NaN   NaN
1       206.23                  NaN   NaN
2       291.23                  NaN   NaN
3       291.23                  NaN   NaN
4       291.23  nose salida viernes   NaN
..         ...                  ...   ...
179     722.37                  NaN   NaN
180     722.37                  NaN   NaN
181     742.37                  NaN   NaN
182     746.87                  NaN   NaN
183     766.87                  NaN   NaN

[184 rows x 9 columns]
         FECHA  diff_TOTAL  diff_tarjeta  diff_saldo_sin_inversion  \
0   2025-01-23      -10.71          5.00                     -6.75
1   2025-01-30      -10.46          8.50                     -3.00
2   2025-01-31      -13.46          0.00                    -14.50
3   2025-02-03       27.76         26.41                     -2.95
4   2025-02-05      -38.62         23.46                    -50.20
..         ...         ...           ...                       ...
69  2025-08-25       23.00          0.00                      0.00
70  2025-09-04      -72.51          0.00                    -72.51
71  2025-09-07       20.00          0.00                      0.00
72  2025-09-14       20.00          0.00                      0.00
73  2025-09-16       20.00          0.00                      0.00

    diff_notion                                        DESCRIPCION  \
0           0.0                               Wafles y salida majo
1           0.0                                       Hamburguesas
2           0.0                             Comida reconciliacion.
3          54.0                                                NaN
4          34.0  Estuche y kfc23.5.290 dvuelvo Nico, derma 34, ...
..          ...                                                ...
69         23.0                                                NaN
70          0.0                                                NaN
71         20.0                                                NaN
72         20.0                                                NaN
73         20.0                                                NaN

                            DESCRIPCION_NOTION comentario MADRE
0                                          NaN        NaN   NaN
1                                          NaN        NaN   NaN
2                                          NaN        NaN   NaN
3   Papas y majo-|-Pago matricuu carro ($54.0)        NaN   NaN
4                                 Derm ($34.0)        NaN   NaN
..                                         ...        ...   ...
69                           Uber stav ($23.0)        NaN   NaN
70                                         NaN        NaN   NaN
71                           Pago Majo ($20.0)        NaN   NaN
72                           Pago Majo ($20.0)        NaN   NaN
73                  Rectificada frenos ($20.0)        NaN   NaN

[74 rows x 9 columns]
         FECHA  diff_total_yo  diff_tarjeta  diff_saldo_real  \
0   2024-06-21         -31.97         31.97             0.00
1   2024-06-22        -102.52        102.52             0.00
2   2024-06-24          71.92          5.99            77.91
3   2024-06-25         -62.75          0.00           -62.75
4   2024-07-04         -29.35          0.00           -29.35
..         ...            ...           ...              ...
78  2025-05-22         105.25          0.00           105.25
79  2025-05-29         -23.28         23.28             0.00
80  2025-06-01         -46.22         46.22             0.00
81  2025-06-06         -22.50          0.00           -22.50
82  2025-06-10         723.61          0.00           723.61

                        descripcion comentario   madre
0                     Casa res mela        NaN     NaN
1                            Carro         NaN  pagado
2                      Poo me pagan        NaN     NaN
3                      Pastillas 60        NaN     NaN
4   Tienda trago 15,De una padel 14        NaN     NaN
..                              ...        ...     ...
78                              NaN        NaN     NaN
79                              NaN        NaN     NaN
80                              NaN        NaN     NaN
81                              NaN        NaN     NaN
82                              NaN        NaN     NaN

[83 rows x 7 columns]

TypeError: '<' not supported between instances of 'str' and 'Timestamp'

In [ ]:


txt_files_names = ["completo2026_01_14.xlsx", "completo_2025-09-20.xlsx", "diferencias_2025-09-20.xlsx", "diferencias_atipicas3.xlsx"]
lista_dfs = [] # Es mejor guardar todo en una lista y concatenar al final

for file_name in txt_files_names:
    path = os.path.join(project_root, "data", "descripciones", file_name)
    
    # IMPORTANTE: Usamos read_excel porque la extensión es .xlsx
    try:
        df = pd.read_excel(path)
        print(f"Leído exitosamente: {file_name}")
        lista_dfs.append(df)
    except Exception as e:
        print(f"Error al leer {file_name}: {e}")

# Concatenamos todos los DataFrames de la lista
if lista_dfs:
    df_unido = pd.concat(lista_dfs, ignore_index=True)
    
    # Asegúrate de que la columna FECHA sea de tipo datetime antes de ordenar
    df_unido['FECHA'] = pd.to_datetime(df_unido['FECHA'], errors='coerce')
    df_unido.sort_values(by="FECHA", inplace=True)
    
    print("\nDataFrame unido y ordenado por fecha:")
    print(df_unido.head())
else:
    print("No se cargó ningún dato.")

Leído exitosamente: completo2026_01_14.xlsx
Leído exitosamente: completo_2025-09-20.xlsx
Leído exitosamente: diferencias_2025-09-20.xlsx
Leído exitosamente: diferencias_atipicas3.xlsx

DataFrame unido y ordenado por fecha:
         FECHA  TOTAL  SALDO  TARJETA  INVERSION  PAGOS_MENSUAL_MA INTER  \
535 2024-06-21    NaN    NaN      NaN        NaN                     NaN
536 2024-06-22    NaN    NaN      NaN        NaN                     NaN
537 2024-06-24    NaN    NaN      NaN        NaN                     NaN
538 2024-06-25    NaN    NaN      NaN        NaN                     NaN
539 2024-07-04    NaN    NaN      NaN        NaN                     NaN

     NOTIONCUM DESCRIPCION MADRE  diff_TOTAL  diff_tarjeta  \
535        NaN         NaN   NaN         NaN         31.97
536        NaN         NaN   NaN         NaN        102.52
537        NaN         NaN   NaN         NaN          5.99
538        NaN         NaN   NaN         NaN          0.00
539        NaN         NaN   NaN         NaN          0.00

     diff_saldo_sin_inversion  diff_notion DESCRIPCION_NOTION comentario  \
535                       NaN          NaN                NaN        NaN
536                       NaN          NaN                NaN        NaN
537                       NaN          NaN                NaN        NaN
538                       NaN          NaN                NaN        NaN
539                       NaN          NaN                NaN        NaN

     diff_total_yo  diff_saldo_real                      descripcion   madre
535         -31.97             0.00                    Casa res mela     NaN
536        -102.52             0.00                           Carro   pagado
537          71.92            77.91                     Poo me pagan     NaN
538         -62.75           -62.75                     Pastillas 60     NaN
539         -29.35           -29.35  Tienda trago 15,De una padel 14     NaN

In [25]:
df_unido

,FECHA,TOTAL,SALDO,TARJETA,INVERSION,PAGOS_MENSUAL_MA INTER,NOTIONCUM,DESCRIPCION,MADRE,diff_TOTAL,diff_tarjeta,diff_saldo_sin_inversion,diff_notion,DESCRIPCION_NOTION,comentario,diff_total_yo,diff_saldo_real,descripcion,madre
535,2024-06-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.97,NaN,NaN,NaN,NaN,-31.97,0.00,Casa res mela,NaN
536,2024-06-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.52,NaN,NaN,NaN,NaN,-102.52,0.00,Carro,pagado
537,2024-06-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.99,NaN,NaN,NaN,NaN,71.92,77.91,Poo me pagan,NaN
538,2024-06-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,-62.75,-62.75,Pastillas 60,NaN
539,2024-07-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,-29.35,-29.35,"Tienda trago 15,De una padel 14",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,2026-01-05,1.08,28208.41,439.79,28951.0,0.0,1183.46,"Almuerzos 8, Concierto 47",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,2026-01-06,-62.87,28144.46,439.79,28951.0,0.0,1183.46,"Parqueadero 60, Almuerzo 4",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,2026-01-07,-65.12,28142.21,439.79,28951.0,0.0,1183.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,2026-01-08,-69.07,28138.26,439.79,28951.0,0.0,1183.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,2026-01-09,-64.07,28143.26,439.79,28951.0,0.0,1183.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN